name: CI/CD Pipeline

on:
  push:
    branches:
      - dev-L00171125-Abhishek-DGW-132

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Install JSDoc
      run: |
       cd /home/runner/work/DevOps2023-2024-Group3/DevOps2023-2024-Group3/WWA-frontend-master
       npm i -g jsdoc

    - name: Install docdash Theam
      run: |
       cd /home/runner/work/DevOps2023-2024-Group3/DevOps2023-2024-Group3/WWA-frontend-master
       npm i docdash

    - name: Generate JSDocs
      run: |
          cd /home/runner/work/DevOps2023-2024-Group3/DevOps2023-2024-Group3/WWA-frontend-master
          npm run docs

    - name: Commit and push change
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update documentation
        branch: dev-L00171125-Abhishek-DGW-132


    

    

    

   
